サイドバー、スレッドヘッダー部分のダミー文字修正
N310/chat-space pull request #19
Opened 2017-08-05 11:50 UTC by N310

# WHAT
- [ ] サイドバーのダミー文字修正
- [ ]スレッドヘッダーのダミー文字修正

# WHY
- ダミー文字を入れていたテキストやリンク先を正しいものにする

2017-08-05 11:55 UTC, offich requested changes
お時間よろしいときに、修正していただけると幸いです。

2017-08-05 11:55 UTC, r-ume commented on app/views/messages/_sidebar.html.haml
> +      = link_to "/groups/#{belong_group.id}/messages", class: "groupList__link" do
ここは、routesのprefixをお使いになられた方がすっきりします。

2017-08-05 11:55 UTC, r-ume commented on app/views/messages/_sidebar.html.haml
> +          = belong_group.name
**GOOD**
hamlの使いこなせているのがいいですね。

2017-08-05 11:55 UTC, r-ume commented on app/views/messages/_sidebar.html.haml
> +          - new_message = belong_group.messages.order('created_at DESC').first
このようなロジックは、コントローラーに書いていただけると幸いです。

2017-08-05 11:55 UTC, r-ume commented on app/views/messages/index.html.haml
> +            %span #{user.name}
こちらの変数の表示は、hamlの=を使いましょう。

2017-08-05 11:55 UTC, r-ume commented on app/views/messages/index.html.haml
> +        = link_to "Edit", "/groups/#{@group.id}/edit"
こちらも、routesのprefixをお使いいただけると幸いです。

2017-08-05 11:56 UTC, r-ume commented
実際にページがどうなっているのかの画像もお願いいたします。

2017-08-19 02:52 UTC, N310 commented on app/views/messages/_sidebar.html.haml
> +      = link_to "/groups/#{belong_group.id}/messages", class: "groupList__link" do
修正しました。

2017-08-19 02:53 UTC, N310 commented on app/views/messages/index.html.haml
> +        = link_to "Edit", "/groups/#{@group.id}/edit"
修正しました。

2017-08-19 02:55 UTC, N310 commented on app/views/messages/index.html.haml
> +            %span #{user.name}
修正しました。

2017-08-19 03:36 UTC, N310 commented
![screencapture-localhost-3000-groups-1-messages-1503113585695](https://user-images.githubusercontent.com/16056616/29483140-f7db578c-84da-11e7-8f27-a44b252916bd.png)

2017-08-19 03:36 UTC, N310 commented on app/views/messages/_sidebar.html.haml
> +          = belong_group.name
ありがとうございます！

2017-08-19 03:36 UTC, N310 commented on app/views/messages/_sidebar.html.haml
> +          - new_message = belong_group.messages.order('created_at DESC').first
修正しました。
ヘルパーとして追加しました。

2017-08-19 03:48 UTC, offich requested changes
お時間よろしいときに、見ていただければ幸いです。

2017-08-19 03:48 UTC, r-ume commented on app/helpers/application_helper.rb
> +  def get_newmessage(belong_group)
こちらのメソッドの処理は、`messages_controller.rb` に書くようにしましょう。

2017-08-19 03:57 UTC, N310 commented on app/helpers/application_helper.rb
> +  def get_newmessage(belong_group)
なぜヘルパーだとダメなのでしょうか。
コントローラーにアクションとして定義するのと
ヘルパーメソッドとして定義するものは
どのようにわければいいのでしょうか。

2017-08-19 04:04 UTC, r-ume commented on app/helpers/application_helper.rb
> +  def get_newmessage(belong_group)
> なぜヘルパーだとダメなのでしょうか。

1. ヘルパーには、基本モデルのプロパティの表示を変えるためのメソッドを定義します。
今回の例でいうと、`get_newmessage` メソッドは、belong_groupに紐づいているものを表示させるものであり、ある程度のロジックを必要とするものは、helperには書かないのがよしとされています。
2.

2017-08-19 06:11 UTC, N310 commented on app/helpers/application_helper.rb
> +  def get_newmessage(belong_group)
コメントいただきありがとうございます。
今回の処理は`messages_controller.rb`と`groups_controller.rb`の両方に書く必要がありそうでしたので、`group.rb`に記述して呼び出すことにしました。

2017-08-19 06:53 UTC, merged